Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/jammy64"
  config.vm.box = "debian/buster64"
  
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 4
    vb.memory = "4096"
  end
  
  config.vm.provision "shell" do |shell|
    shell.path = "jenkins_install.sh"
  end
end
